### ISSUE TITLE
Machaao API Token?

### ISSUE THREAD

**Issue by toncho11** [machaao/gpt-j-chatbot#11]
Hi,

Why is the Machaao API Token required? 
It says that it can run locally. The GPT-J model is downloaded locally, but it still requires online services from Machaao. 
Is it  possible to run without an API key?

**Comment by unixguru2k** [comment]
We are a cloud platform that facilitates building, growing and monetizing your chat app.
And above is a sample repository for folks not looking to go through the pain of hosting your own messaging infrastructure
